// grAB-version 1.0 beta - 2/4/14
// written by: Brandon Morrison
// updates at: http://github.com/bamtron5
// or: http://brandonam.com
// REQUIRED - jQuery 1.7.1 or higher
// not inteneded for commercial use, CC Attribution Non-Commercial 4.0 International
// http://creativecommons.org/licenses/by-nc/4.0/deed.en_US


//DESCRIPTION
////////////////////////////////////////////////
//grAB is a light-weight AB testing platform that can replace html, change css, or redirect based
//off cookie settings generated by grAB or by the"cam" value passed to the URL.  
//The examples below should be used on the page you wish to alter.
///////////////////////////////////////////////

////////////////////////////////////////////////
////////////////////////////////////////////////
/////////////grAB example uses//////////////////
////////////////////////////////////////////////
////////////////////////////////////////////////

//CHANGE CSS
//grAB.changeCss(campaign, element, css);
//grAB.changeCss('string','jQuery element', '[array]');
//grAB.changeCss('a','#billboard2', ["background","url(../images/MCPC_HP_Billboard.jpg) no-repeat", "border","thin red solid"]);

//REDIRECT
//grAB.changeUrl(campaign, full url);
//grAB.changeUrl('string','string');
//grAB.changeUrl('b','http://ustechsupport.com');

//REPLACE HTML w/ HTML from FILE
//grAB.replaceHtml(string, jQuery element, file path without first "/");
//grAB.replaceHtml('string', 'jQuery element', 'string');
//grAB.replaceHtml('d','#billboard2','grab/index-d.html');


////////////////////////////////////////////////
////////////////////////////////////////////////
/////////////GET and SET Cookie/////////////////
///////////Determine the campaign///////////////
////////////////////////////////////////////////
////////////////////////////////////////////////
 


function grAB_campaign(){
	var currCampaign;
	grABparam = location.search;
	grABparam = grABparam.replace("?","");
    grABparam = grABparam.split("&");
	for(x=0; x <= grABparam.length; x++){
		if(grABparam[x].indexOf("cam") > -1){
			currCampaign = grABparam[x].replace("cam=","");
			return currCampaign;
			return false;
		}
	}
};


function grAB_getCookie(){
	/*tell me something about this user*/
	var cookie = document.cookie;
	var cookieObj = cookie.split(';');
	return cookieObj;
};


function grAB_setCookie(){
	/*Set the campaign in side the cps cookie... never allow people to deviate from campaign URL.  SET THIS TO A SWITCH SO REGULAR TESTING CAN TAKE PLACE.*/	
};

grAB_getCookie();
grAB_setCookie();



/////grAB Class
grAB = {
	changeCss: function(cam, element, style)
	{	/*PARAM: what element or obj full of element selectors. style is an object.  OBJ: property/style */
		var currCampaign = grAB_campaign();
		if(currCampaign != cam){
			return false;	
		} else {
			x=0;
			for(i = 0; i <= style.length; i++){
				if(x == 0){
					var property = style[i];
					x++;	
				} else {
					var value = style[i];
					$(element).css(property,value);
					x = 0;
				}
			}
		};
	},
	replaceHtml: function(cam, element, html)
	{	/*replace html snippet*/
		var currCampaign = grAB_campaign();
		if(currCampaign != cam){
			return false;	
		} else {
			$(element).load('http://' + document.location.host + "/" +html);
			$(element).css('display','block');
		}
	},
	changeUrl: function(cam, redirect)
	{	/*redirect the page*/
		var currCampaign = grAB_campaign();
		if(currCampaign != cam){
			return false;	
		} else {
			$('*').css('display','none');
			document.location.href = redirect;
		}
	},
	changeImage: function(cam, image, newimage)
	{	/*imagery on this page to be set?*/
		var currCampaign = grAB_campaign();
		if(currCampaign != cam){
			return false;	
		} else {
			$(image).attr(src,"newimage");
		}
	}
}




////////////////////////////////////////////////
////////////////////////////////////////////////
/////////////FOR LOGGING of INFO////////////////
////////////////////////////////////////////////
////////////////////////////////////////////////

	function grAB_loginfo(){
		/*send omniture which version / which page.  this way analytics can be assessed from omniture.  less convolution. also set campaign in cookie*/
		var currCampaign = grAB_campaign();
	}
	
	grAB_loginfo();	